update recipe requirements for 2.10
conda-forge/asdf-feedstock pull request #50
Opened 2022-02-23 16:52 UTC by CagtayFabry

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] ~~Reset the build number to `0` (if the version changed)~~
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

## Changes
This draft updates the 2.10 release to have matching python requirements as found in the python package

2022-02-23 16:54 UTC, CagtayFabry commented
@WilliamJamieson this draft is an example how to update the 2.10 release on conda to match the requirements specified in `setup.cfg` of `asdf`

I expect the CI to fail here since the `asdf-standard` is not available on conda yet

2022-03-03 02:29 UTC, WilliamJamieson requested changes
With these changes and the merger of #18146, you should take this PR out of draft.

2022-03-03 02:29 UTC, WilliamJamieson commented on recipe/meta.yaml
> +    - asdf-transform-schemas >=0.2.0
```suggestion
    - asdf-standard >=1.0.1
    - asdf-transform-schemas >=0.2.2 
```
These are the versions that are or will be available on conda-forge starting out.

2022-03-03 17:59 UTC, WilliamJamieson approved these changes

2022-03-03 17:59 UTC, merged

2022-03-04 08:11 UTC, CagtayFabry commented
thank you @WilliamJamieson I wasn't around for a few days

glad to see this working now 👍